# dito fish completion — generated by `dito completion fish`
function __dito_complete
    set -l ct (commandline -ct)
    set -l out (dito __complete (commandline -opc)[2..-1] "$ct")
    set -l directive $out[-1]
    set -e out[-1]
    if set -q out[1]
        printf '%s\n' $out
    end
    switch $directive
        case ':dirs'
            __fish_complete_directories "$ct"
        case ':files'
            __fish_complete_path "$ct"
    end
end
complete -c dito -f -a '(__dito_complete)'
