#!/usr/bin/env python3
"""gengtk.py -- GTK4/libadwaita colour overrides per theme.

    gengtk.py              every theme (catppuccin-mocha gets an empty one)
    gengtk.py paper void   just these

Writes theme/.config/theme/<name>/gtk.css. theme-switch points
~/.local/state/theme/gtk.css at it, and ~/.config/gtk-4.0/gtk.css imports
that link, so libadwaita apps take the theme's accent and surfaces on their
next start (GTK does not reload user CSS live). Adwaita vs Adwaita-dark is
still chosen by theme.json apps.gtk*; these colours are written for that
variant. Colours are flattened: a translucent GTK window is Hyprland's job
(window opacity rules), not the CSS's.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
from themecolor import THEMES, Model, generated_themes, hex6, load, mix, over  # noqa: E402

HEAD = "/* {label}: generated by theme/.config/theme/tools/gengtk.py from theme.json. Do not edit. */\n"


def css(m):
    btnbg = over(m.layer(m.tintAlpha), m.window) if m.glass else None
    accent_text = m.accent if m.dark else m.focus      # standalone accent, legible on the window
    v = {
        "accent-bg-color": m.press if m.t.get("roles", {}).get("container") else m.accent,
        "accent-fg-color": m.onPress if m.t.get("roles", {}).get("container") else m.onAccent,
        "accent-color": accent_text,
        "destructive-bg-color": m.err, "destructive-fg-color": m.base if m.dark else "#ffffff",
        "destructive-color": m.err, "success-color": m.ok, "warning-color": m.warn, "error-color": m.err,
        "window-bg-color": m.window, "window-fg-color": m.text,
        "view-bg-color": m.base, "view-fg-color": m.text,
        "headerbar-bg-color": m.window, "headerbar-fg-color": m.text,
        "headerbar-backdrop-color": m.window,
        "sidebar-bg-color": m.crust if not m.dark else m.window, "sidebar-fg-color": m.text,
        "sidebar-backdrop-color": m.crust if not m.dark else m.window,
        "secondary-sidebar-bg-color": m.window, "secondary-sidebar-fg-color": m.text,
        "card-bg-color": btnbg or (m.base if not m.dark else m.s0), "card-fg-color": m.text,
        "dialog-bg-color": m.base if not m.dark else m.window, "dialog-fg-color": m.text,
        "popover-bg-color": m.base if not m.dark else m.s0, "popover-fg-color": m.text,
        "thumbnail-bg-color": m.s0, "thumbnail-fg-color": m.text,
    }
    v = {k: hex6(c) for k, c in v.items()}
    out = [HEAD.format(label=m.label)]
    # libadwaita >= 1.6 reads CSS variables; the @define-color names cover older
    # libadwaita and GTK4 apps that still reference the named colours.
    out.append(":root {\n" + "".join(f"  --{k}: {c};\n" for k, c in v.items()) + "}\n")
    out += [f"@define-color {k.replace('-', '_').removesuffix('_color') + '_color'} {c};\n" for k, c in v.items()]
    return "".join(out)


def build(name):
    d = os.path.join(THEMES, name)
    if name == "catppuccin-mocha":
        body = ("/* catppuccin-mocha: no overrides -- plain Adwaita-dark, as before themes existed.\n"
                "   Present so the state link always resolves (a missing @import warns in every app). */\n")
    else:
        body = css(Model(load(name)))
    with open(os.path.join(d, "gtk.css"), "w") as f:
        f.write(body)
    print(f"{name}: ok")


def main(argv):
    for n in argv or ["catppuccin-mocha"] + generated_themes():
        build(n)


if __name__ == "__main__":
    main(sys.argv[1:])
